### ISSUE TITLE
Error during partial diffusion

### ISSUE THREAD

**Issue by ane1233** [ramellose/manta#14] opened 2023-11-20 20:34 UTC
Has anyone encountered this issue?  I tried increasing the number of iterations and changing the subset parameter, as mentioned in another thread, and neither fixed the problem. Is there another option?

I have about 300 samples in my dataset.

2023-11-20 14:31:02,254 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2023-11-20 14:31:02,256 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2023-11-20 14:31:02,257 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2023-11-20 14:31:02,258 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2023-11-20 14:31:02,260 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2023-11-20 14:31:02,261 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2023-11-20 14:31:02,262 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2023-11-20 14:31:02,264 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
Traceback (most recent call last):
  File "/home/cmstaley/syal0007/.local/bin/./manta", line 8, in <module>
    sys.exit(main())
  File "/home/cmstaley/syal0007/.local/lib/python3.8/site-packages/manta/main.py", line 283, in main
    results = cluster_graph(network, limit=args['limit'], max_clusters=args['max'],
  File "/home/cmstaley/syal0007/.local/lib/python3.8/site-packages/manta/cluster.py", line 112, in cluster_graph
    scoremat, partials = partial_diffusion(graph=graph, iterations=iterations, limit=limit, subset=subset,
  File "/home/cmstaley/syal0007/.local/lib/python3.8/site-packages/manta/flow.py", line 312, in partial_diffusion
    pos_sums = result[b][pos_results]
IndexError: list index out of range

**Comment by ramellose** [comment] 2023-11-21 08:11
Thank you for your interest in manta! 
Can you provide a reproducible example, either based on your data or using your data, that captures this error?
Despite your high sample number, it is possible the matrices are still converging to zero. In theory, this can happen with perfectly balanced networks. Those are unusual, but can occur.

**Comment by ane1233** [comment] 2023-11-21 16:01
Thank you so much for the quick response, here is the graphml file I am using. I am also providing the initial shared file and taxonomy file, which I used before I did my workup to create the graphml file in case my workup could be causing the error. Let me know if I can help in any other way.  

Many thanks! 

[QQ3study.network.graphml.txt](https://github.com/ramellose/manta/files/13428471/QQ3study.network.graphml.txt)
[QQ3.final.taxonomy.txt](https://github.com/ramellose/manta/files/13428477/QQ3.final.taxonomy.txt)
[QQ3.final.opti_mcc.shared.txt](https://github.com/ramellose/manta/files/13428480/QQ3.final.opti_mcc.shared.txt)

**Comment by ane1233** [comment] 2023-11-21 19:09
Thank you so much for the quick response, here is the graphml file I am using called "QQ3new.network.graphml". I am also providing the initial shared file and taxonomy file, which I used before I did my workup to create the graphml file in case my workup could be causing the error. Let me know if I can help in any other way.  I had to make them txt files to upload on here, let me know if any problems arise due to that. 

Many thanks! 

[QQ3.final.taxonomy.txt](https://github.com/ramellose/manta/files/13430115/QQ3.final.taxonomy.txt)
[QQ3.final.opti_mcc.shared.txt](https://github.com/ramellose/manta/files/13430116/QQ3.final.opti_mcc.shared.txt)
[QQ3new.network.graphml.txt](https://github.com/ramellose/manta/files/13430122/QQ3new.network.graphml.txt)

**Comment by ramellose** [comment] 2023-11-22 08:08
The following issues seem to be happening:

- The graph has multiple components (disconnected taxa etc) - when keeping only the largest component, the algorithm completes successfully
- The graph is a balanced network; the info message recommends using the Kernighan-Lin algorithm instead
- Random clustering outperforms manta, likely because the graph doesn't have a strong clustered structure. 

The image below shows what the network looks like after it is clustered with manta. As you can see. only one taxon, Otu00001, is assigned to a different cluster. I suspect this is because the network is not very clustered (in terms of weighted edges) to begin with; although there are groups of nodes with positive associations between them, they also have a lot of negative associations between them. 
![image](https://github.com/ramellose/manta/assets/32293364/96e9f3b6-bc94-4dcc-ad23-ab5e72e13cac)

Because the clustering structure of your network does not seem to be defined by positive- and negatively weighted edges, it may make more sense to use an algorithm that uses edge density instead of weight to cluster. You could try using MCL or Louvain clustering on the positive associations only, I expect those would perform well!

**Comment by ramellose** [comment] 2023-12-14 17:10
Closing this issue unless there are additional problems, feel free to reopen in that case!

**Closed as completed by ramellose** 2023-12-14 17:10 UTC
